config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :stations, dependent: :destroy
  accepts_nested_attributes_for :stations, allow_destroy: true, reject_if: :all_blank
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  def index
    @properties = Property.all
  end

  def show
    @stations = @property.stations
  end

  def new
    @property = Property.new
    2.times { @property.stations.build }
  end 

  def edit
    @property.stations.build
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to properties_path, notice: "物件を登録しました！"
    else
      render :new
    end
  end

  def update
    if @property.update(property_params)
      redirect_to properties_path, notice: "物件を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @property.destroy
    redirect_to properties_url
  end

  private
  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(
      :name, 
      :rent, 
      :address, 
      :age, 
      :other,
    stations_attributes: [
      :route_name,
      :station_name,
      :access,
      :property_id,
      :id,
      :_destroy,
    ],
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mofmof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>
      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :rent %><br>
    <%= form.number_field :rent %>円
  </div>
  <div class="field">
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>
  <div class="field">
    <%= form.label :age %><br>
    <%= form.number_field :age %>年
  </div>
  <div class="field">
    <%= form.label :other %><br>
    <%= form.text_area :other %>
  </div>
  <%= form.fields_for :stations do |station| %>
  <div>
    <h1>最寄駅<%= 1 + station.index.to_i %></h1>
  </div>
　　<div class="field">
  　　<%= station.label :route_name %><br>
  　　<%= station.text_field :route_name %>
　　</div>
　　<div class="field">
  　　<%= station.label :station_name %><br>
  　　<%= station.text_field :station_name %>
　　</div>
　　<div class="field">
  　　<%= station.label :access %><br>
  　　 <%= station.text_field :access %>分<br>
　　</div>  
  <% end %>
  <div class="actions">
    <%= form.submit "登録する" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', property: @property %>

<%= link_to '詳細', @property %> |
<%= link_to '戻る', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.rent %>円</td>
        <td><%= property.address %></td>
        <td><%= property.age %>年</td>
        <td><%= property.other %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件登録', new_property_path %>

app/views/properties/new.html.erb
<h1>物件登録</h1>

<%= render 'form', property: @property %>

<%= link_to '戻る', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>物件名:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @property.rent %>円
</p>

<p>
  <strong>住所:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @property.age %>年
</p>

<p>
  <strong>備考:</strong>
  <%= @property.other %>
</p>
<% @stations.each.with_index(1) do |station, i| %>
<h2>最寄駅<%= i %></h2>
<p>
  <strong>路線名:</strong>
  <%= station.route_name %>
</p>
<p>
  <strong>駅名:</strong>
  <%= station.station_name %>
</p>
<p>
  <strong>徒歩分数:</strong>
  <%= station.access %>分
</p>
<% end %>

<%= link_to '編集', edit_property_path(@property) %> |
<%= link_to '戻る', properties_path %>